# Generated by Django 5.1.3 on 2025-03-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=100)),
                ("nazwisko", models.CharField(max_length=100)),
                ("indeks", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.CharField(max_length=200)),
                ("telefon", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
